version: '3.8'

x-environment:
  &default-environment
  MONGODB_URL:
  NATIVE_MONGO_URL:
  COLLECTION: 'toLower'
  OP_NAME: 'toLower'
  RESULT_FIELD: 'toLowerField'
  EXPRESSION: "{$$toLower: '$$name' }"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      <<: *default-environment

  locust:
    build:
      context: locust/
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    environment:
      <<: *default-environment
    depends_on:
      - app

  native-app:
    build: .
    ports:
      - "8081:8081"
    environment:
      <<: *default-environment
      SERVER_PORT: 8081

  native-app-locust:
    build:
      context: locust/
      dockerfile: Dockerfile
    ports:
      - "8090:8089"
    environment:
      <<: *default-environment
    depends_on:
      - native-app

  data-gen:
    build:
      context: data-gen/
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      <<: *default-environment
    depends_on:
      - locust

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - app

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
      GF_USERS_ALLOW_SIGN_UP: "false"
    depends_on:
      - prometheus

volumes:
  grafana-data:
