global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8080']
  - job_name: 'spring-boot-native'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['native-app:8081']