{
 "title": "Dashboard For Aggregation",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "RPM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPM Aggregated over 3m",
   "type": "timeseries",
   "description": "It gives rpm to the api for the operation aggregated over 3m interval",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (operation, instance) (rate(mongodb_operation_time_seconds_count[3m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "DB Call latency P 50",
   "type": "timeseries",
   "description": "GIves P50 latency of the operation",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "mongodb_operation_time_seconds{quantile=\"0.5\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Call latency P 95",
   "type": "timeseries",
   "description": "GIves P50 latency of the operation",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "mongodb_operation_time_seconds{quantile=\"0.95\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Call latency P 99",
   "type": "timeseries",
   "description": "GIves P99 latency of the operation",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "mongodb_operation_time_seconds{quantile=\"0.99\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}